### PR TITLE
Add E5770 usb loaders

### PR DESCRIPTION
**Pull request by ValdikSS**

### CODE REVIEW

**Comment by ValdikSS** [comment]
Это другая версия, не та, которая есть сейчас в репозитории. Полагаю, отличия минимальны.

**Comment by myan33** [comment]
ZONG E5573CS-322 1456 VER NEED USBLOADER

**Comment by myan33** [comment]
PLEASE PROVIDE TELENOR E8372H-608 WORKING USBLAODER

**Comment by ValdikSS** [comment]
@myan33 I don't have it.

**Comment by myan33** [comment]
I MODIFY A TELENOR E8372H-608 1406 LATEST VER
I SHARE EVERYONE THIS FIRMWRAE

https://drive.google.com/file/d/0B0S5tKoHZmTzZ0lmd3JwVG1aZlk/view?usp=sharing

**Comment by myan33** [comment]
ZONG E8372H-153 RESET FIXED SOLUTION

https://drive.google.com/file/d/0B0S5tKoHZmTzZ0lmd3JwVG1aZlk/view?usp=sharing

**Comment by ValdikSS** [comment]
This is not an appropriate place to share any firmwares. This is a pull request, not a chat. Please refrain from commenting offtopic here.

**Comment by myan33** [comment]
really THEN WHY YOU ASKING HERE USBLOADER,THIS FORUM NOT A FOR ASKINGA  USBLOADERS?

**Comment by myan33** [comment]
E5770 USBLSAFE https://drive.google.com/file/d/0B0S5tKoHZmTzekRiUVRrX1ZoYXM/view?usp=sharing

**Comment by ValdikSS** [comment]
This is not a forum, this is a software repository. I'm not asking for usbloader, I provide them. You can see proposed files in "Files changed" section.

**Review by myan33 — COMMENTED** [review]
wrong loader  loader size 5.80 mb not a 5.79

**Comment by myan33** [comment]
really if you can provide any loaders ,provide me working loader of zong and telenor operator changed partition  table of loader,not loader work on device ,can you mod a loader??????????

**Comment by myan33** [comment]
please provide me loader

**Comment by ValdikSS** [comment]
I'm not a developer of this software. I just found the loader for E5770 and made a pull request to the main repository. Please read how git and github works. I won't answer you further.

**Comment by myan33** [comment]
then you patch a loader of e5770 which person patch a loader it can 100% mod a loaders

please help dear

**Comment by myan33** [comment]
then you patch a loader of e5770 which person patch a loader it can 100% mod a loaders

please help dear

**Comment by myan33** [comment]
then you patch a loader of e5770 which person patch a loader it can 100% mod a loaders

please help dear

**Comment by ValdikSS** [comment]
Open source is very simple: if you need it, you do it yourself. Do you not ask for something in an non-appropriate place with capslock on. @forth32, the developer of this program, is sick of people with manners like yours and just ignores everybody. He won't answer your questions, and I'm not skilled to answer them.

**Comment by myan33** [comment]
you are also beggar ,which are use forth program ,devolpy your base not begg to  forth32 you have 0% skill that reason you used forth program,you have no skills

**Comment by ValdikSS** [comment]
I have no idea what are you talking about. In this commit I'm adding files, not asking for them.
If you don't understand what's going on, thinking it's a forum and don't want to read where you are writing, then shut the fuck up and leave my pull request.

**Comment by siyan11** [comment]
forth32 always help pk peoples i see
not help anyone 
my advice to you forth32 better then publicity you stopped your this forum ,make fool to people, make zong solution private base earn  money,you are not a real person forth,no 1 fake person you are

**Comment by siyan11** [comment]
forth32 always help pk peoples i see
not help anyone 
my advice to you forth32 better then publicity you stopped your this forum ,make fool to people, make zong solution private base earn  money,you are not a real person forth,no 1 fake person you are

**Comment by siyan11** [comment]
forth32 always help pk peoples i see
not help anyone 
my advice to you forth32 better then publicity you stopped your this forum ,make fool to people, make zong solution private base earn  money,you are not a real person forth,no 1 fake person you are

**Comment by siyan11** [comment]
forth32 always help pk peoples i see
not help anyone 
my advice to you forth32 better then publicity you stopped your this forum ,make fool to people, make zong solution private base earn  money,you are not a real person forth,no 1 fake person you are

**Comment by siyan11** [comment]
forth32 always help pk peoples i see
not help anyone 
my advice to you forth32 better then publicity you stopped your this forum ,make fool to people, make zong solution private base earn  money,you are not a real person forth,no 1 fake person you are

**Comment by siyan11** [comment]
forth32 always help pk peoples i see
not help anyone 
my advice to you forth32 better then publicity you stopped your this forum ,make fool to people, make zong solution private base earn  money,you are not a real person forth,no 1 fake person you are

**Comment by saqi755** [comment]
Please send melink to download zong and telenor wingle links

Thanks

On 20 Aug 2017 12:17, "myan33" <notifications@github.com> wrote:

PLEASE PROVIDE TELENOR E8372H-608 WORKING USBLAODER

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/forth32/balong-usbdload/pull/38#issuecomment-323568479>,
or mute the thread

**Comment by saqi755** [comment]
I need telenor wingle links please approve request for this

**Pull request merged**
